# Programs

export TOP_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

# Project properties
export REQ_DB_SCHEMA_VERSION := 1

# User setable variables
export PROJECT_NAME := p0nygramm
export INSTALL_DIR := /srv
export CONFIG_DIR_NAME := config
export STATIC_WEBCONTENT_DIR_NAME := webcontent
export UPLOADS_DIR_NAME := uploads
export BUILDMODE := debug

export PROJECT_PATH := $(INSTALL_DIR)/$(PROJECT_NAME)
export CONFIG_PATH := $(PROJECT_PATH)/$(CONFIG_DIR_NAME)
export STATIC_WEBCONTENT_PATH := $(PROJECT_PATH)/$(STATIC_WEBCONTENT_DIR_NAME)
export UPLOADS_PATH := $(PROJECT_PATH)/$(UPLOADS_DIR_NAME)

create-dir-structure:
	mkdir -p $(PROJECT_PATH)
	mkdir -p $(CONFIG_PATH)

parse-template:
	$(MAKE) -C $(TOP_DIR)/ressources/config
